version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dockerUser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dockerTestDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
      
  backend:
    image: dorazidocker/opracion-docker-back
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: dorazidocker/opracion-docker-front
    ports:
      - "8888:80"
    depends_on:
      - backend


volumes:
  postgres_data:
